# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.BooleanField(default=False)),
                ('area', models.BooleanField(default=False)),
                ('finding_place', models.BooleanField(default=False)),
                ('process', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('daytime_phone', models.CharField(max_length=100)),
                ('bedroom', models.DecimalField(decimal_places=0, max_digits=2)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('location_area', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-full_name'],
            },
        ),
    ]
